spring:
  application:
    name: service-registry-server

eureka:
  instance:
    hostname: service-registry-server
    prefer-ip-address: false
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://service-registry-server:8761/eureka/

server:
  port: 8761