
FROM openjdk:8-jre-slim
EXPOSE 8888
RUN mkdir /app
COPY system/config-server/build/libs/config-server*.jar /app/app.jar
ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]