
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
#        auth-service:
#          path: /uaa/** #path that will be intercepted
#          url: auth-service #which url the request will e mapped to
#          stripPrefix: false #if zuul should replace the "/uaa/" segment
#          sensitiveHeaders:

        account-service:
          - id: account-service
            uri: https://account-service.org

      discovery:
          locator:
            enabled: true
          locatorlower-case-service-id: true

server:
  port: 8080